services:
   php:
     build: .
     environment:
      - DISCODING_DB_HOST=db
      - DISCODING_DB_NAME=discoding
      - DISCODING_DB_USER=discoding
      - DISCODING_DB_PASSWORD=discoding
     volumes:
       - ./:/var/www/html/
     ports:
       - 8080:80

   db:
     image: mysql:9
     volumes:
       - ./discoding.sql:/docker-entrypoint-initdb.d/1.sql
       - dbdata:/var/lib/mysql
     ports:
      - 3307:3306
     environment:
       MYSQL_ROOT_PASSWORD: discoding
       MYSQL_DATABASE: discoding
       MYSQL_USER: discoding
       MYSQL_PASSWORD: discoding

   phpmyadmin:
     image: phpmyadmin/phpmyadmin:5.1.1
     ports:
       - '9090:80'
     environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: discoding
     depends_on:
       - db

volumes:
  dbdata: {}
